# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- script: |
    npm install -g appcenter-cli
    appcenter login --token feebdff44f99eecaa582e06442080b2621793f1d
  displayName: 'Login into app-center'

- task: AppCenterTest@1
  inputs:
    artifactsDirectory: '$(Build.BinariesDirectory)/debug-app.apk'
    frameworkOption: 'appium'
    appiumBuildDirectory: '$(Agent.HomeDirectory)'
    credentialsOption: 'serviceEndpoint'
    localeOption: 'en_US'